### ISSUE TITLE
20532 D Version - Only 4 Modules/Labs?

### ISSUE THREAD

**Issue by k-a-west** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#206]
The current contents here on Github currently only include Allfiles & Instructions for Modules 1-4.  Is this by-design, reflecting a re-working and compaction of the course into only 4 Modules, or are there additional Allfiles and Instructions expected to be added into Github soon to cover the labs in Modules 5-11?

In referencing the currently-available Skillpipe manual for the 20532D version - Important note, 'D' version, *not* the 'C' version -  there are 11 Modules listed.  Also, in the files available via the DLC for 20532D we have references to 11 individual Modules.

**Comment by seesharprun** [comment]
This is a major bug. It's showing as 11 labs to me but when I log out of GitHub and view the repo as an anonymous user, I only see 4 labs.

This is a breaking bug and I have a 48 hour SLA to get these resolved. I will either have a resolution or update posted in 48 hours.

Thanks for bringing my attention to this, I got a few reports of people not seeing all of the labs that were marked as "no-repro".

**Comment by jdevr1es** [comment]
This appears not to have been resolved. Is a resolution near, as I am starting this class today.

**Comment by liketaurus** [comment]
I have this class on this week. And I decide to use an old (20532C v3.2.1) solution files and make some mix from old and new lab instructions...

**Comment by jdevr1es** [comment]
I asked my Courseware people to look into this with MS. If we can’t get it resolved, I will probably try the same thing. 

Sent from Mail for Windows 10

**Comment by seesharprun** [comment]
So after a ton of headache and pain, the bug in the repository has a work-around.

I still can't commit directly to the repository without "unwinding" history again. It's very strange and I have no clue why it's happening after getting expert opinions and trying to fix this issue myself for weeks.

The remaining labs were brought in with Pull Request #208 today.

The latest release of the D Labs are here: <https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/releases/latest>.

The labs are built automatically but you can build it yourself manually if you would like. The instructions are here: <https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/tree/master/.build>.

I hope this gets you unstuck! I apologize again for how long this took, I was under the gun to come up with a solution and the fastest way to get a solution this week was to delete everything and start over.
